/**
 * 자동 명함 시안 생성 API
 */

import type { CardInfo, CardDraft } from './types';
import { getSupabaseClient } from '../../../../utils/supabase/client';
import { projectId } from '../../../../utils/supabase/info';

const MOCK_MODE = import.meta.env.DEV && import.meta.env.VITE_PRINT_MOCK_MODE === 'true';

const API_BASE_URL =
  import.meta.env.VITE_FUNCTIONS_URL ||
  `https://${projectId}.supabase.co/functions/v1/make-server-98397747`;

async function getAuthHeaders(): Promise<Record<string, string>> {
  const supabase = getSupabaseClient();
  const {
    data: { session },
  } = await supabase.auth.getSession();

  const headers: Record<string, string> = {
    'content-type': 'application/json',
  };

  if (session?.access_token) {
    headers.Authorization = `Bearer ${session.access_token}`;
    headers['X-User-Token'] = session.access_token;
  }

  return headers;
}

/**
 * 3개 시안 자동 생성 (단면/양면 지원)
 */
export async function autoGenerateDrafts(payload: {
  project_id: string;
  typography_kit_id: string;
  logo_asset_id: string;
  card_info: CardInfo;
  qr_enabled: boolean;
  is_double_sided?: boolean; // ✅ 추가
}): Promise<{
  draft_group_id: string;
  mode: 'starter' | 'professional' | 'refiner';
  sides: {
    front: Array<{
      variant: 'A' | 'B' | 'C';
      card_doc_id: string;
      proof_signed_url: string;
      omitted_fields: string[];
      preflight: { ok: boolean; errors: string[] };
    }>;
    back?: Array<{
      variant: 'A' | 'B' | 'C';
      card_doc_id: string;
      proof_signed_url: string;
      omitted_fields: string[];
      preflight: { ok: boolean; errors: string[] };
    }>;
  };
}> {
  if (MOCK_MODE) {
    // Mock response
    await new Promise((resolve) => setTimeout(resolve, 2000));
    
    const groupId = crypto.randomUUID();
    const isDouble = payload.is_double_sided ?? false;
    
    const frontDrafts = ['A', 'B', 'C'].map((variant) => ({
      variant: variant as 'A' | 'B' | 'C',
      card_doc_id: crypto.randomUUID(),
      proof_signed_url: 'data:application/pdf;base64,...',
      omitted_fields: [],
      preflight: { ok: true, errors: [] },
    }));
    
    const backDrafts = isDouble
      ? ['A', 'B', 'C'].map((variant) => ({
          variant: variant as 'A' | 'B' | 'C',
          card_doc_id: crypto.randomUUID(),
          proof_signed_url: 'data:application/pdf;base64,...',
          omitted_fields: [],
          preflight: { ok: true, errors: [] },
        }))
      : undefined;
    
    return {
      draft_group_id: groupId,
      mode: 'professional',
      sides: {
        front: frontDrafts,
        back: backDrafts,
      },
    };
  }
  
  // Real API call
  const headers = await getAuthHeaders();
  const response = await fetch(
    `${API_BASE_URL}/api/card/auto-generate`,
    {
      method: 'POST',
      headers,
      body: JSON.stringify(payload),
    }
  );
  
  if (!response.ok) {
    throw new Error(await response.text());
  }
  
  return await response.json();
}

/**
 * 시안 선택 및 Print PDF 생성 (양면 지원)
 */
export async function selectAndLockCard(payload: {
  front_card_doc_id: string;
  back_card_doc_id?: string;
}): Promise<{
  chosen_card_doc: { id: string };
  print_export: { id: string };
  signed_url: string;
  deleted_drafts: string[];
}> {
  if (MOCK_MODE) {
    // Mock response
    await new Promise((resolve) => setTimeout(resolve, 1000));
    
    return {
      chosen_card_doc: { id: payload.front_card_doc_id },
      print_export: { id: crypto.randomUUID() },
      signed_url: 'data:application/pdf;base64,...',
      deleted_drafts: [crypto.randomUUID(), crypto.randomUUID()],
    };
  }
  
  // Real API call
  const headers = await getAuthHeaders();
  const response = await fetch(
    `${API_BASE_URL}/api/card/select-and-lock`,
    {
      method: 'POST',
      headers,
      body: JSON.stringify(payload),
    }
  );
  
  if (!response.ok) {
    throw new Error(await response.text());
  }
  
  return await response.json();
}

/**
 * 출고 요청 생성
 */
export async function createFulfillmentJob(payload: {
  export_id: string;
  print_options: {
    qty: number;
    paper_type?: string;
    finish?: string;
  };
  shipping: {
    receiver: string;
    phone: string;
    address: string;
    postal_code?: string;
    memo?: string;
  };
}): Promise<{
  job: {
    id: string;
    status: string;
    created_at: string;
  };
}> {
  if (MOCK_MODE) {
    // Mock response
    await new Promise((resolve) => setTimeout(resolve, 800));
    
    return {
      job: {
        id: crypto.randomUUID(),
        status: 'PDF_LOCKED',
        created_at: new Date().toISOString(),
      },
    };
  }
  
  // Real API call
  const headers = await getAuthHeaders();
  const response = await fetch(
    `${API_BASE_URL}/api/fulfillment/create`,
    {
      method: 'POST',
      headers,
      body: JSON.stringify(payload),
    }
  );
  
  if (!response.ok) {
    throw new Error(await response.text());
  }
  
  return await response.json();
}
