/**
 * 양면 지원 3개 시안 선택 UI
 * - Starter: 앞면 3개만
 * - Professional: 앞면 3개 + 뒷면 3개
 * - Refiner: 사용자 선택
 */

import React, { useState } from 'react';
import { Card } from '../../../app/components/ui/card';
import { Button } from '../../../app/components/ui/button';
import { Badge } from '../../../app/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../../../app/components/ui/tabs';
import { Check, AlertCircle, Info, Download, FileText, Package, Layers } from 'lucide-react';
import { toast } from 'sonner';
import type { CardInfo } from './types';
import { autoGenerateDrafts, selectAndLockCard, createFulfillmentJob } from './api';
import { FulfillmentForm, type FulfillmentData } from './FulfillmentForm';

interface CardConceptPickerDoubleProps {
  project_id: string;
  typography_kit_id: string;
  logo_asset_id: string;
  card_info: CardInfo;
  qr_enabled: boolean;
  is_double_sided?: boolean;
  onComplete?: () => void;
}

type Step = 'select' | 'finalized';

interface DraftResponse {
  draft_group_id: string;
  mode: 'starter' | 'professional' | 'refiner';
  sides: {
    front: Array<{
      variant: 'A' | 'B' | 'C';
      card_doc_id: string;
      proof_signed_url: string;
      omitted_fields: string[];
      preflight: { ok: boolean; errors: string[] };
    }>;
    back?: Array<{
      variant: 'A' | 'B' | 'C';
      card_doc_id: string;
      proof_signed_url: string;
      omitted_fields: string[];
      preflight: { ok: boolean; errors: string[] };
    }>;
  };
}

export function CardConceptPickerDouble(props: CardConceptPickerDoubleProps) {
  const logoFontFamily = 'Inter';
  const bodyFontFamily = 'Inter';
  const [step, setStep] = useState<Step>('select');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<DraftResponse | null>(null);
  
  const [selectedFront, setSelectedFront] = useState<string | null>(null);
  const [selectedBack, setSelectedBack] = useState<string | null>(null);
  
  const [printPdfUrl, setPrintPdfUrl] = useState<string | null>(null);
  const [exportId, setExportId] = useState<string | null>(null);
  const [fulfillmentJobId, setFulfillmentJobId] = useState<string | null>(null);
  
  const isDouble = result?.sides.back != null;
  const canFinalize = isDouble ? (!!selectedFront && !!selectedBack) : !!selectedFront;
  
  // 자동 생성
  const handleGenerate = async () => {
    setLoading(true);
    try {
      const response = await autoGenerateDrafts({
        project_id: props.project_id,
        typography_kit_id: props.typography_kit_id,
        logo_asset_id: props.logo_asset_id,
        card_info: props.card_info,
        qr_enabled: props.qr_enabled,
        is_double_sided: props.is_double_sided,
        logo_font_family: logoFontFamily,
        body_font_family: bodyFontFamily,
      });
      
      setResult(response);
      setSelectedFront(null);
      setSelectedBack(null);
      setPrintPdfUrl(null);
      setExportId(null);
      setFulfillmentJobId(null);
      
      toast.success(`${response.sides.front.length}개의 시안이 생성되었습니다!`);
    } catch (error: any) {
      console.error('Generation error:', error);
      toast.error(error.message || '시안 생성 중 오류가 발생했습니다.');
    } finally {
      setLoading(false);
    }
  };
  
  // 선택 확정
  const handleFinalize = async () => {
    if (!selectedFront) return;
    
    setLoading(true);
    try {
      const payload: {
        front_card_doc_id: string;
        back_card_doc_id?: string;
        logo_font_family: string;
        body_font_family: string;
        card_name?: string;
      } = {
        front_card_doc_id: selectedFront,
        logo_font_family: logoFontFamily,
        body_font_family: bodyFontFamily,
        card_name: props.card_info.name,
      };
      
      if (isDouble && selectedBack) {
        payload.back_card_doc_id = selectedBack;
      }
      
      const response = await selectAndLockCard(payload);
      
      setPrintPdfUrl(response.signed_url);
      setExportId(response.print_export.id);
      setStep('finalized');
      
      toast.success('인쇄용 PDF가 생성되었습니다!');
    } catch (error: any) {
      console.error('Selection error:', error);
      toast.error(error.message || '선택 확정 중 오류가 발생했습니다.');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async () => {
    if (!printPdfUrl) {
      toast.error('다운로드할 PDF가 없습니다.');
      return;
    }

    try {
      const response = await fetch(printPdfUrl);
      if (!response.ok) {
        throw new Error('PDF 다운로드에 실패했습니다.');
      }

      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `MyBrands_Print_${isDouble ? 'Double' : 'Single'}.pdf`;
      a.click();
      URL.revokeObjectURL(url);

      toast.success('PDF 다운로드 완료!');
    } catch (error: any) {
      console.error('Download error:', error);
      toast.error(error.message || 'PDF 다운로드 중 오류가 발생했습니다.');
    }
  };
  
  // 출고 요청
  const handleFulfillmentSubmit = async (data: FulfillmentData) => {
    if (!exportId) {
      toast.error('Export ID가 없습니다.');
      return;
    }
    
    setLoading(true);
    try {
      const response = await createFulfillmentJob({
        export_id: exportId,
        print_options: {
          qty: data.qty,
          paper_type: data.paper_type,
          finish: data.finish,
        },
        shipping: {
          receiver: data.receiver,
          phone: data.phone,
          address: data.address,
          postal_code: data.postal_code,
          memo: data.memo,
        },
      });
      
      setFulfillmentJobId(response.job.id);
      toast.success('출고 요청이 완료되었습니다!');
      
      if (props.onComplete) {
        setTimeout(() => props.onComplete?.(), 1500);
      }
    } catch (error: any) {
      console.error('Fulfillment error:', error);
      toast.error(error.message || '출고 요청 중 오류가 발생했습니다.');
    } finally {
      setLoading(false);
    }
  };
  
  // ========== 렌더링 ==========
  
  // 초기 상태: 생성 버튼
  if (!result) {
    return (
      <div className="text-center py-8">
        <Button onClick={handleGenerate} disabled={loading} size="lg">
          {loading ? '시안 생성 중...' : 'AI로 3개 시안 자동 생성'}
        </Button>
      </div>
    );
  }
  
  // Step 1: 시안 선택
  if (step === 'select') {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-lg font-semibold flex items-center gap-2">
              {isDouble && <Layers className="w-5 h-5" />}
              AI가 생성한 3가지 시안
            </h3>
            <p className="text-sm text-muted-foreground mt-1">
              {isDouble
                ? '앞면과 뒷면에서 각각 1개씩 선택하세요'
                : '마음에 드는 디자인을 선택하세요'}
            </p>
          </div>
          
          <Button onClick={handleGenerate} variant="outline" size="sm" disabled={loading}>
            다시 생성
          </Button>
        </div>
        
        {/* 앞면 선택 */}
        <div className="space-y-3">
          <div className="flex items-center gap-2">
            <Badge>앞면 (정보면)</Badge>
            {selectedFront && <Check className="w-4 h-4 text-green-600" />}
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {result.sides.front.map((draft) => {
              const isSelected = selectedFront === draft.card_doc_id;
              
              return (
                <Card
                  key={draft.card_doc_id}
                  className={`overflow-hidden transition-all cursor-pointer ${
                    isSelected
                      ? 'ring-2 ring-blue-500 shadow-lg'
                      : 'hover:shadow-md'
                  }`}
                  onClick={() => setSelectedFront(draft.card_doc_id)}
                >
                  <div className="p-3 border-b bg-muted/20 flex items-center justify-between">
                    <Badge variant={isSelected ? 'default' : 'secondary'}>
                      시안 {draft.variant}
                    </Badge>
                    {isSelected && <Check className="w-4 h-4 text-green-600" />}
                  </div>
                  
                  <div className="aspect-[9/5] bg-muted/10 flex items-center justify-center">
                    <span className="text-sm text-muted-foreground">앞면 미리보기</span>
                  </div>
                  
                  {draft.omitted_fields.length > 0 && (
                    <div className="p-2 bg-yellow-50 border-t text-xs text-yellow-800">
                      자동 생략: {draft.omitted_fields.join(', ')}
                    </div>
                  )}
                </Card>
              );
            })}
          </div>
        </div>
        
        {/* 뒷면 선택 (양면인 경우) */}
        {isDouble && result.sides.back && (
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <Badge variant="outline">뒷면 (로고/도메인)</Badge>
              {selectedBack && <Check className="w-4 h-4 text-green-600" />}
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {result.sides.back.map((draft) => {
                const isSelected = selectedBack === draft.card_doc_id;
                
                return (
                  <Card
                    key={draft.card_doc_id}
                    className={`overflow-hidden transition-all cursor-pointer ${
                      isSelected
                        ? 'ring-2 ring-purple-500 shadow-lg'
                        : 'hover:shadow-md'
                    }`}
                    onClick={() => setSelectedBack(draft.card_doc_id)}
                  >
                    <div className="p-3 border-b bg-muted/20 flex items-center justify-between">
                      <Badge variant={isSelected ? 'default' : 'secondary'}>
                        시안 {draft.variant}
                      </Badge>
                      {isSelected && <Check className="w-4 h-4 text-green-600" />}
                    </div>
                    
                    <div className="aspect-[9/5] bg-muted/10 flex items-center justify-center">
                      <span className="text-sm text-muted-foreground">뒷면 미리보기</span>
                    </div>
                  </Card>
                );
              })}
            </div>
          </div>
        )}
        
        {/* 확정 버튼 */}
        <div className="flex justify-center pt-4">
          <Button
            onClick={handleFinalize}
            disabled={!canFinalize || loading}
            size="lg"
          >
            {loading
              ? '처리 중...'
              : isDouble
              ? '앞/뒷면 선택 확정 → 인쇄 PDF 생성'
              : '선택 확정 → 인쇄 PDF 생성'}
          </Button>
        </div>
        
        {/* 안내 */}
        <Card className="p-4 bg-muted/30">
          <div className="flex gap-3">
            <Info className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
            <div className="text-sm space-y-1">
              <p className="font-medium">자동 생성 시스템 안내</p>
              <ul className="text-muted-foreground space-y-1 text-xs">
                <li>• AI가 폰트 크기를 자동으로 조정하여 텍스트가 잘리지 않습니다</li>
                <li>• 공간이 부족하면 주소/웹사이트를 자동으로 생략할 수 있습니다</li>
                <li>• 모든 시안은 인쇄 안전 영역 검사를 통과했습니다</li>
                {isDouble && <li>• 양면 명함은 2페이지 PDF로 생성됩니다 (1p=앞, 2p=뒤)</li>}
              </ul>
            </div>
          </div>
        </Card>
      </div>
    );
  }
  
  // Step 2: 확정 완료 (PDF 다운로드 + 출고 요청)
  if (step === 'finalized') {
    return (
      <div className="space-y-6">
        {/* 헤더 */}
        <div className="text-center">
          <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <Check className="w-8 h-8 text-green-600" />
          </div>
          <h3 className="text-2xl font-bold mb-2">명함 디자인이 확정되었습니다!</h3>
          <p className="text-muted-foreground">
            {isDouble ? '양면 인쇄용 PDF가 생성되었습니다 (2페이지)' : '인쇄용 PDF가 생성되었습니다'}
          </p>
        </div>
        
        {/* 탭: PDF 미리보기 vs 출고 요청 */}
        <Tabs defaultValue="preview" className="w-full">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="preview" className="flex items-center gap-2">
              <FileText className="w-4 h-4" />
              PDF 미리보기
            </TabsTrigger>
            <TabsTrigger value="fulfillment" className="flex items-center gap-2">
              <Package className="w-4 h-4" />
              출고 요청
            </TabsTrigger>
          </TabsList>
          
          {/* PDF 미리보기 */}
          <TabsContent value="preview" className="space-y-4 mt-4">
            <Card className="overflow-hidden">
              <div className="aspect-[9/5] bg-muted">
                {printPdfUrl ? (
                  <iframe title="print-pdf" src={printPdfUrl} className="w-full h-full" />
                ) : (
                  <div className="h-full flex items-center justify-center">
                    <FileText className="w-16 h-16 text-muted-foreground" />
                  </div>
                )}
              </div>
            </Card>
            
            <div className="flex gap-3 justify-center">
              <Button size="lg" onClick={handleDownload} disabled={!printPdfUrl}>
                <Download className="w-4 h-4 mr-2" />
                PDF 다운로드
              </Button>
              
              <Button variant="outline" size="lg" onClick={() => setStep('select')}>
                다른 시안 선택
              </Button>
            </div>
          </TabsContent>
          
          {/* 출고 요청 */}
          <TabsContent value="fulfillment" className="mt-4">
            {fulfillmentJobId ? (
              <Card className="p-8 text-center">
                <div className="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4">
                  <Package className="w-8 h-8 text-blue-600" />
                </div>
                <h3 className="text-xl font-bold mb-2">출고 요청 완료!</h3>
                <p className="text-muted-foreground mb-6">
                  요청 번호: <code className="px-2 py-1 bg-muted rounded">{fulfillmentJobId.slice(0, 8)}</code>
                </p>
                <p className="text-sm text-muted-foreground">
                  1-2 영업일 내 제작이 시작되며, 배송은 3-5 영업일 소요됩니다.
                </p>
              </Card>
            ) : (
              <FulfillmentForm onSubmit={handleFulfillmentSubmit} loading={loading} />
            )}
          </TabsContent>
        </Tabs>
      </div>
    );
  }
  
  return null;
}
